services:
  db:
    image: postgres:18.1-alpine
    container_name: iabots-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - iabots-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - iabots-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: deployment/docker/migrate.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-local}
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
    networks:
      - iabots-net
    restart: "no"
      
  seed:
    build:
      context: .
      dockerfile: deployment/docker/seed.Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
    networks:
      - iabots-net
    restart: "no"

  api:
    build:
      context: .
      dockerfile: deployment/docker/api.Dockerfile
    container_name: iabots-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT:-5001}:${APP_PORT:-5001}"
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_PORT: "${APP_PORT:-5001}"
      GIN_MODE: ${GIN_MODE:-debug}
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
    networks:
      - iabots-net


volumes:
  iabots-db-data:

networks:
  iabots-net:
    driver: bridge
