version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: iabots-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - iabots-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - iabots-net

  api:
    build:
      context: .
      dockerfile: deployment/docker/api.Dockerfile
    container_name: iabots-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - iabots-net
    volumes:
      - ./:/app

volumes:
  iabots-db-data:

networks:
  iabots-net:
    driver: bridge
